### ISSUE TITLE
[Question] astropy and CAMB for w0waCDM

### ISSUE THREAD

**Issue by andrejdvornik** [halomod/hmf#113]
For some testing purposes I recently try to use a more general cosmology from astropy (namely the `w0waCDM` and `Flatw0waCDM`) that is then passed to the hmf (and halomod). As far as I understand CAMB, it should work with those quite ok, but then I do get the following error:

`ValueError: CAMB will only work with LCDM or wCDM cosmologies`

This might be pycamb version dependent, but I thought I might ask here if that is actually the case, or is it something not implemented in `transfer_models`?

**Comment by steven-murray** [comment]
Hi @andrejdvornik, this is certainly just something that I haven't had time to interface with CAMB. I would be very happy for a contribution that made it possible! I can lead you through some of the details if you need.
