### ISSUE TITLE
HMF sampler does not take into account Mmax (upper limit on logmass) [BUG]

### ISSUE THREAD

**Issue by ashaeres** [halomod/hmf#161]
Although it is possible to specify the range of the HMF (`Mmin` and `Mmax`) when creating a `MassFunction` object, the `_choose_halo_masses_num` function in hmf/helpers/sample.py ignores `Mmax` altogether. It generates random numbers between 0 and 1, when in fact the normalized mass range might not go all the way to 0 (1 corresponds to `Mmin`, but `Mmax` is not necessarily 0), forcing the function to extrapolate outside the data range, and resulting in a sample of masses that is not restricted to the specified mass interval.

1. Specify both the minimum logmass and the maximum logmass in the sampler, as well as a large number of samples N: ``` hmf.helpers.sample.sample_mf(N, 11, Mmax=13)```
2. Convert the output masses to log10
3. Check that the sampled log masses lie within the logmass interval [11;13]

We would expect the sampler to generate masses within the specified interval. For this the line `x = np.random.random(int(N))` in the `_choose_halo_masses_num` function should be replaced with `x = np.random.uniform(low=np.min(h.ngtm / h.ngtm[0]), high=1.0, size=N)`.

**Comment by steven-murray** [comment]
Thanks for the issue, @ashaeres! Does #162 fix the issue for you?

**Comment by ashaeres** [comment]
Hi Steven, yes I think this would also work! Thank you for your help :)
