### ISSUE TITLE
Calculating Cumulative Stellar Mass Density for a given redshift range.

### ISSUE THREAD

**Issue by seVenVo1d** [halomod/hmf#167]
Hello, 

I am a M.Sc. Physics Student at Istanbul Technical University.  I need to to plot this graph, for my master studies:

![image](https://user-images.githubusercontent.com/45866787/221183998-1be04f45-4285-4811-9a28-5ff316b640c9.png)

While looking through the articles, I came across with this github repo and it seems very useful. However, I cannot seem to write the code to plot the graph. It seems that the graph is plotting cumulative stellar mass density (CSMD). 

In `hmf` I guess that would correspond to the `mf.rho_gtm`..? As a result, I have tried the write the code as:

```
import matplotlib.pyplot as plt  # The necessary plotting library
import numpy as np               # Numerical array library

from hmf import MassFunction     # The main hmf class

mf = MassFunction(z=7, hmf_model="PS")

plt.plot(mf.m, mf.rho_gtm)
plt.xscale('log')
plt.yscale('log')

plt.xlabel(r"Mass, $[h^{-1}M_\odot]$")
plt.ylabel(r"$\rho (>M_{\odot})$, $[M_{\odot}h^2{\rm Mpc}^{-3}]$")
plt.show()
```

However my redshift range should be in between `[7,9]`.  To achieve that, I have tried using the `update`method but I couldn't figure it out...

 Also, is it possible to obtain (or add) star formation efficiency and the baryon fraction to the code?

Article Ref: arXiv:2301.00347v2

Thanks,
Arman

**Comment by steven-murray** [comment]
Hi @seVenVo1d, I think `hmf` can provide a basis for what you want to do, but you'll need to add to it. You'll need to assign stellar mass to halos with some prescription (there are many out there) then probably need to do the cumulative integral yourself (this part is very easy using `scipy.integrate`). 

Furthermore, if you want to *average* over z=7-9 you could do something like (this is me writing code off the top of my head, please don't trust it):

```python
h = hmf.MassFunction()

smf = np.zeros((h.m.size, 100))
for i, z in enumerate(np.linspace(7, 9, 100)):
    h.update(z=z)
    mf = h.dndm
    smf[:, i] = assign_stellar_masses(mf)

average_smf = np.mean(smf, axis=1)
```

Obviously, you'd need to write the `assign_stellar_masses` function given whatever prescription you want, and you can also add other processing into the script. 

Finally, I'll mention the https://github.com/halomod/halomod package, which extends HMF and assigns galaxy counts to halos according to common HOD prescriptions. It may or may not be a help.

**Comment by seVenVo1d** [comment]
Hi again!. Thanks for the fast response. I was looking through the code and article for the past two days. 

> You'll need to assign stellar mass to halos with some prescription

I guess that corresponds to the HMF function(?). In the article it is given by *Press-Schechter HMF*

>  Then probably need to do the cumulative integral yourself (this part is very easy using scipy.integrate).

Yes, it seems that is the right way.

> Obviously, you'd need to write the `assign_stellar_masses` function given whatever prescription you want, and you can also add other processing into the script.

I did not understand this part. I mean why do I have to define `assign_stellar_masses` function...or what  should be the purpose of it...

In the meantime, in another article I have found this graph.

![image](https://user-images.githubusercontent.com/45866787/221403854-0decd912-cc57-4087-a90c-12a4c01944ec.png)

This is done for only particular redshift value, so I thought doing this would be easier. However, somehow I cannot plot the exact one. It is also possible that I am taking some other parameters for `MassFunction()`, but putting that aside, I have couple of questions related to the code and corresponding mathematical equations.

1. Does `mf.rho_gtm` corresponds to

$$
\rho (>M_{\rm halo}, z) = \int_{M_{\rm halo}}^{\infty}dMM\frac{dn(M,z)}{dM}
$$

?

2. If that is the case,  the units of the `mf.rho_gtm`  is given by

$$
[M_{\odot}h^2Mpc^{-3}]
$$

right?

3. Similarly `mf.m` is the

$$
M_{\rm halo}
$$

and the unit is given by

$$
[M_{\odot}h^{-1}]
$$

?

Thanks,
Arman

**Comment by steven-murray** [comment]
Yes, your math is all correct. But the HMF is the halo mass function, not the stellar mass function. It says nothing in itself about how much stellar mass is in each halo -- it only gives you the Dark Matter mass in each halo. You need a prescription for assigning stellar mass when you have halo mass.

**Comment by seVenVo1d** [comment]
> You need a prescription for assigning stellar mass when you have halo mass.

Oh I see your point. It is given by

$$
M_{\odot} = \epsilon f_bM_halo
$$

Is it a way to add this into the `MassFunction()` ? I was just using it only during the plotting via 

    mf_rho_new_1 = epsilon_1*f_b*mf.rho_gtm*h0_P18**(-2)
    mf_m_new_1 = epsilon_1*f_b*mf.m*h0_P18**(1)

Is this a wrong method to apply. I also only did this beacause epsilon and f_b are constant.

**Comment by steven-murray** [comment]
If your prescription of stellar to halo mass is constant, this is reasonable, but that is not a very physical model, so you might not see close correspondence to data. Typically the stellar-mass-to-halo-mass relation (SMHM) is a nonlinear function of halo mass, decreasing at both low and high masses due to feedback etc.

**Comment by seVenVo1d** [comment]
ı see. That seems important indeed. In the article that I have been reading the relation is given by a constant..that is why I took that like that. Now, I guess the only thing I need to do is to perform the cumulative integral.

**Comment by seVenVo1d** [comment]
I would like to ask one last thing...Why the result of the `mf.rho_gtm` is an array of values and not a single value....It seems to me that we should obtain a single value...I just cannot seem to understand the logic..

Thanks,
Arman

**Comment by steven-murray** [comment]
`rho_gtm` is the mass density of the universe for all DM inside halos of mass M or greater. So, it is a function of M.

**Comment by seVenVo1d** [comment]
Thanks a lot. I understand it now...I guess that is why there are `Mmin`, `Mmax` and `dlog10m` parameters... It calculates the integral for each point from `Mmin` to `Mmax`, with step size `dlog10m`

**Comment by steven-murray** [comment]
That's right!

**Comment by seVenVo1d** [comment]
Thanks a lot. I really appreciate it.
