### ISSUE TITLE
[Feature Req] Including Planck 18 Cosmology

### ISSUE THREAD

**Issue by seVenVo1d** [halomod/hmf#168]
**Describe the solution you'd like**
I believe it would be nice to add the `Planck18` cosmology from `astropy`

If it is also possible, I would like to contribute to the project by adding this feature. I guess first I have to add `Planck18` to the 

    from astropy.cosmology import FLRW, WMAP5, WMAP7, WMAP9, Planck13, Planck15  # noqa

line in `src/hmf/cosmology/cosmo.py` and later on update the docs.

**Comment by seVenVo1d** [comment]
I also want to contribute to the project in general. In current stage, I guess I can try to help to improve the docs and maybe try to do some other small stuff. It's also kind of hard for me to learn and follow the development steps, since I have never contributed to any project before but I'll try my best to learn and follow them.

**Comment by steven-murray** [comment]
@seVenVo1d your contributions will be much appreciated! The best way to learn is to play around with it and make small contributions!

You're right, adding Planck18 should be as easy as adding it to that line. Documentation updates are also a very valuable contribution.

**Comment by seVenVo1d** [comment]
That is great to hear. Then, I am going to try to do some updates and create a PR until the end of the week.

**Comment by steven-murray** [comment]
The `get_hmf` function is in here: https://github.com/halomod/hmf/blob/dev/src/hmf/helpers/functional.py -- the spelling should be `req_quantities` so you could definitely fix that if it's wrong! It's fine if some files use one cosmo and others use another.

**Comment by seVenVo1d** [comment]
@steven-murray
> The get_hmf function is in here: https://github.com/halomod/hmf/blob/dev/src/hmf/helpers/functional.py -- the spelling should be req_quantities so you could definitely fix that if it's wrong! 

I'll definitely fix that in the next PR. 

>It's fine if some files use one cosmo and others use another.

That's great. I have also noticed that `matplotlib` is not installed during the setup of `hmf`. I'll also try to add that, if I can.

**Comment by seVenVo1d** [comment]
This is now fixed with PR #170
