### ISSUE TITLE
simpson in scipy 1.14.0

### ISSUE THREAD

**Issue by rreischke** [halomod/hmf#219]
Dear Steven,

**Describe the bug**
I cannot import hmf anymore with scipy-version 1.14.0. 

`ImportError: cannot import name 'simps' from 'scipy.integrate' (/home/robert/anaconda3/lib/python3.12/site-packages/scipy/integrate/__init__.py). Did you mean: 'simpson'?
`

**To Reproduce**
Fresh installation of hmf with no prior installation of scipy of an older version.

**Expected behavior**

 - OS: Ubuntu
 
**Additional context**
`simps` is deprecated and should be called `simpson` in ever call. A quick look into the source code tells me that `even` keyword also would need to go. In principle `simpson` can be called in the same manner as `numpy.trapz`.

Cheers,
Robert

**Comment by steven-murray** [comment]
Thanks @rreischke, yes indeed, this will be fixed in #218
